backup script

diff --git a/orchestrate_pustakalaya b/orchestrate_pustakalaya
--- a/orchestrate_pustakalaya
+++ b/orchestrate_pustakalaya
@@ -114,9 +114,28 @@ fi
 
 
 if [[ "$1" == "dump_sql" ]] ; then
-        backup_file=${ls $local_backup *bz2 | tail -n 1 }
-        echo "backup file is $backup_file"
+        backup_file_bz2=$(ls $local_backup | tail -n 1 )
+        echo "backup file is $backup_file_bz2"
+        pushd $local_backup
+        if [[ -f $backup_file_bz2 ]] ; then
+             
+             bzip2 -dk $backup_file_bz2 
+             backup_file_sql=${backup_file_bz2%.*}
+             docker exec postgres_01 bash -c "psql --username pustakalaya_user -d pustakalaya -f /pg_backups/backup/daily/pustakalaya/$backup_file_sql"
+             if [ $? -eq 0 ]; then
+                   echo "Dumpped  from $backup_file_sql"
+                   rm -rvf $local_backup/*sql
 
+             else
+                   echo "Failed Dumping file"
+             fi
+
+             
+        else
+             echo "No backup file found. Please backup first"
+       fi
+       popd
+#        tar -jxf $backup_file -C /tmp
         # if [[ -f ./src/db_dump/pustakalaya01.sql ]] ; then
         #           docker exec postgres_01 bash -c "psql --username pustakalaya_user -d pustakalaya -f /src/db_dump/pustakalaya01.sql"
         # fi
